Link against libzip/zlib when USE_INCLUDED_{LIBZIP,ZLIB}=OFF is used
lib3MF.so is not explicitly linked against libzip or zlib even when
USE_INCLUDED_LIBZIP=OFF or USE_INCLUDED_ZLIB=OFF are used. These
libraries therefore need to be specified manually during linking,
otherwise errors like the following occur:

/usr/bin/ld: lib3mf.so.2.0.0.0: undefined reference to `deflateInit2_'

This can be immediately observed when trying to compile lib3mf with

cmake -DUSE_INCLUDED_LIBZIP=OFF -DUSE_INCLUDED_ZLIB=OFF
      -DLIB3MF_TESTS=ON

The solution is to link lib3mf against all the necessary libraries so
that they can be pulled in automatically during linking. With this
change, compilation with the test suite enabled as shown above works.